spring:
  datasource:
    url: jdbc:mysql://samchuck-workshop.ccmvab7gazv8.ap-northeast-2.rds.amazonaws.com:3306/samchuck_workshop
    username: samchuck
    password: samchuck
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: 915A27039D447019B7E9F0BC9D3F7D6D03E417D0D98D57279984376CACA11B44
  token-validity-in-seconds: 86400

